name: Build and deploy ASP.NET Core backend to Azure Web App - activityfinder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build backend
        run: dotnet build ./AFBack --configuration Release

      - name: Publish backend
        run: dotnet publish ./AFBack -c Release -o ./publish-backend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./publish-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C3B32C8E61B749C482143E991CFC9243 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BA1577011A58442F973BA1B46185F645 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E232503888C344728E0811F9D44D6657 }}

      - name: Deploy backend to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'activityfinder'
          slot-name: 'Production'
          package: .
